import 'package:personal_finance/core/constants/enums.dart';

/// Asigna una categoría a un comercio usando palabras clave locales
/// (rápido, sin red). Devuelve `null` si no lo reconoce, para que el
/// llamador pueda recurrir a la IA.
class MerchantCategorizer {
  const MerchantCategorizer();

  static const Map<String, List<String>> _rules = {
    'comida': [
      'comida',
      'almuerzo',
      'cena',
      'desayuno',
      'refaccion',
      'refacción',
      'helado',
      'restaurante',
      'restaurant',
      'cafe',
      'café',
      'coffee',
      'starbucks',
      'mcdonald',
      'burger',
      'pizza',
      'pollo campero',
      'campero',
      'kfc',
      'subway',
      'taco',
      'sushi',
      'domino',
      'wendy',
      'little caesars',
      'pan',
      'panaderia',
      'panadería',
      'comedor',
      'uber eats',
      'rappi',
      'pedidosya',
      'hugo',
      'didi food',
      'food',
    ],
    'supermercado': [
      'walmart',
      'paiz',
      'la torre',
      'super',
      'despensa',
      'maxi despensa',
      'pricesmart',
      'costco',
      'market',
      'mercado',
      'grocery',
      'bodega',
      'econo',
      'carrefour',
      'soriana',
      'oxxo',
      'tienda',
    ],
    'transporte': [
      'transporte',
      'pasaje',
      'uber',
      'didi',
      'indriver',
      'cabify',
      'taxi',
      'bus',
      'metro',
      'transmetro',
      'parqueo',
      'parking',
      'peaje',
      'lyft',
    ],
    'gasolina': [
      'gasolina',
      'diesel',
      'gasolinera',
      'shell',
      'texaco',
      'puma',
      'uno ',
      'esso',
      'chevron',
      'gas station',
      'combustible',
    ],
    'suscripciones': [
      'netflix',
      'spotify',
      'disney',
      'hbo',
      'max ',
      'prime video',
      'amazon prime',
      'youtube',
      'apple.com',
      'icloud',
      'google one',
      'google storage',
      'chatgpt',
      'openai',
      'claude',
      'xbox',
      'playstation',
      'nintendo',
      'crunchyroll',
      'paramount',
      'deezer',
    ],
    'compras': [
      'amazon',
      'aliexpress',
      'shein',
      'temu',
      'mercado libre',
      'ebay',
      'zara',
      'h&m',
      'nike',
      'adidas',
      'mall',
      'store',
      'shop',
      'apple store',
      'best buy',
      'curacao',
      'elektra',
      'siman',
      'cemaco',
    ],
    'salud': [
      'doctor',
      'medicina',
      'consulta',
      'farmacia',
      'pharmacy',
      'cruz verde',
      'galeno',
      'meykos',
      'hospital',
      'clinica',
      'clínica',
      'laboratorio',
      'dentista',
      'medic',
      'óptica',
      'optica',
    ],
    'servicios': [
      'tigo',
      'claro',
      'movistar',
      'eegsa',
      'energuate',
      'empagua',
      'agua',
      'luz',
      'electricidad',
      'internet',
      'cable',
      'telefono',
      'teléfono',
      'at&t',
      'verizon',
    ],
    'entretenimiento': [
      'cine',
      'cinepolis',
      'cinépolis',
      'cinemark',
      'steam',
      'bar ',
      'discoteca',
      'concierto',
      'ticket',
      'boleto',
      'teatro',
      'museo',
    ],
    'educacion': [
      'curso',
      'colegiatura',
      'universidad',
      'colegio',
      'escuela',
      'udemy',
      'coursera',
      'platzi',
      'libreria',
      'librería',
      'duolingo',
    ],
    'hogar': [
      'home depot',
      'ferreteria',
      'ferretería',
      'ikea',
      'novex',
      'renta',
      'alquiler',
      'muebles',
    ],
  };

  static const Map<String, List<String>> _incomeRules = {
    'salario': ['salario', 'sueldo', 'nomina', 'nómina', 'planilla', 'payroll'],
    'reembolso': ['reembolso', 'devolucion', 'devolución', 'refund'],
    'transferencia': [
      'transferencia',
      'te envi',
      'recibiste',
      'deposito',
      'depósito',
    ],
  };

  String? categorize(String merchant, {TransactionType? type}) {
    // Se compara al inicio de palabra para que "pan" no coincida con "japan".
    final text =
        ' ${merchant.toLowerCase().replaceAll(RegExp(r"[^a-z0-9áéíóúüñ.&']+"), ' ')} ';
    if (text.trim().isEmpty) return null;
    final rules = type == TransactionType.income ? _incomeRules : _rules;
    for (final entry in rules.entries) {
      if (entry.value.any((k) => text.contains(' $k'))) return entry.key;
    }
    return null;
  }
}
