// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:personal_finance/core/config/app_config.dart';
import 'package:personal_finance/core/config/firebase_options_dev.dart';
import 'package:personal_finance/core/config/firebase_options_prod.dart';

/// Default [FirebaseOptions] that dynamically routes between Dev and Prod
/// configurations based on the active runtime environment.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return AppConfig.isProduction
        ? ProdFirebaseOptions.currentPlatform
        : DevFirebaseOptions.currentPlatform;
  }
}
