// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your DEV Firebase app.
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DevFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIreL8PjQKV7fPEW301M5LIfxtZeMXFUM',
    appId: '1:116411792004:android:a713a79228fc59a773e0d1',
    messagingSenderId: '116411792004',
    projectId: 'personalfinancedev-e972f',
    storageBucket: 'personalfinancedev-e972f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdcEMx70SIl5uYIvmOzBRyRADrXjVc8VI',
    appId: '1:116411792004:ios:3fec80f6377d2f9173e0d1',
    messagingSenderId: '116411792004',
    projectId: 'personalfinancedev-e972f',
    storageBucket: 'personalfinancedev-e972f.firebasestorage.app',
    iosBundleId: 'com.grullondev.personalFinance',
  );
}
