// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your PRODUCTION Firebase app.
/// Replace placeholder values with your actual Firebase Production credentials.
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'ProdFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-YOUR-PROD-ANDROID-API-KEY-HERE',
    appId: '1:116411792004:android:a713a79228fc59a773prod', // Replace with your Prod Android App ID
    messagingSenderId: '116411792004',
    projectId: 'personalfinance-prod', // Replace with your Prod Project ID
    storageBucket: 'personalfinance-prod.firebasestorage.app', // Replace with your Prod Storage Bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-YOUR-PROD-IOS-API-KEY-HERE',
    appId: '1:116411792004:ios:3fec80f6377d2f9173prod', // Replace with your Prod iOS App ID
    messagingSenderId: '116411792004',
    projectId: 'personalfinance-prod', // Replace with your Prod Project ID
    storageBucket: 'personalfinance-prod.firebasestorage.app', // Replace with your Prod Storage Bucket
    iosBundleId: 'com.grullondev.personalFinance',
  );
}
